---
setup_directory: ~/.setup
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: false

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/NiekKeijzer/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "{{ setup_directory }}/dotfiles"

homebrew_group: brew
homebrew_installed_packages:
  - autoconf
  - composer
  - direnv
    # - flock
  - fnm
  - gcc
  - git 
  - go
  - gpg
  - hadolint 
  - hcloud 
  - helm
  - iperf 
  - jq
  - k3d
  - kubernetes-cli
  - libevent
  - libsass
  - libuv
  - mcrypt
  - minikube
  - nmap 
  - node
  - openssl
  - pipx
  - pyenv 
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - readline
  - ssh-copy-id
  - speedtest-cli 
  - stow
  - sqlite
  - telnet 
  - terminal-notifier
  - terraform 
  - tor
  - wget 
  - zsh 
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - bitwarden
  - cyberduck
  - daisydisk
  - docker 
  - firefox
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - insomnia
  - iterm2
  - mailspring
  - nextcloud 
  - opera
  - pycharm
  - spotify
  - sublime-text
  - the-unarchiver
  - tunnelblick 
  - vagrant
  - vienna 
    # - whatpulse
  - whatsapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: 
  - @quasar/cli
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

pipx_packages: 
  - ansible
  - cookiecutter
  - netaddr
  - pre-commit

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
